package A4_Flights;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.Scanner;

public class FlightsMainForm extends javax.swing.JFrame implements ActionListener, Location.LocationFinder {

    Location[] locations = null;
    Flight[] allFlights = null;
    FlightSchedule schedule = null;

    public FlightsMainForm() {
        initComponents();
        initComboQuery();
        initComboFormat();
        initComboReport();

        txtStatus.setText("No data loaded");
        activateReadyState(false);

        this.pack();
    }

    private void activateReadyState(boolean bReady) {
        txtLocationsFile.setEnabled(!bReady);
        txtFlightsFile.setEnabled(!bReady);
        btnLoad.setEnabled(!bReady);

        btnAllFlightsDisplayFormat.setEnabled(bReady);
        btnAllFlightsArchiveFormat.setEnabled(bReady);
        comboQuery.setEnabled(bReady);
        comboParameter.setEnabled(bReady);
        comboFormat.setEnabled(bReady);
        comboReport.setEnabled(bReady);
        btnQuery.setEnabled(bReady);
        btnReport.setEnabled(bReady);
        txtOutput.setEnabled(bReady);

        if (bReady)
            actionPerformed(null);
    }

    private void initComboQuery() {
        comboQuery.removeAllItems();
        comboQuery.addItem(Common.DESTINATION);
        comboQuery.addItem(Common.FLIGHT_TYPE);
        comboQuery.addItem(Common.POLICY_ERRORS);
        comboQuery.setSelectedIndex(0);
        comboQuery.addActionListener(this);
    }

    private void initComboFormat() {
        comboFormat.removeAllItems();
        comboFormat.addItem(Common.DISPLAY_FORMAT);
        comboFormat.addItem(Common.ARCHIVE_FORMAT);
    }

    private void initComboReport() {
        comboReport.removeAllItems();
        comboReport.addItem(Common.SUMMARY_FLIGHT_TYPE);
        comboReport.addItem(Common.SUMMARY_DESTINATION);
        comboReport.addItem(Common.POLICY_ERRORS);
    }

    /**
     * What to do when the selection in the query combo box changes.
     *
     * @param e
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        comboParameter.removeAllItems();
        String queryType = comboQuery.getSelectedItem().toString();
        if (queryType.equals(Common.FLIGHT_TYPE)) {
            comboParameter.addItem(Common.CARGO);
            comboParameter.addItem(Common.PASSENGER);
            comboParameter.addItem(Common.TRAINING);
        } else if (queryType.equals(Common.DESTINATION))
            for (Location loc : locations)
                comboParameter.addItem(loc.getLocationCode() + " (" + loc.getCity() + ", " + loc.getCountry() + ")");
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLocationsFile = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFlightsFile = new javax.swing.JTextField();
        btnLoad = new javax.swing.JButton();
        btnAllFlightsDisplayFormat = new javax.swing.JButton();
        btnAllFlightsArchiveFormat = new javax.swing.JButton();
        txtStatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnQuery = new javax.swing.JButton();
        comboParameter = new javax.swing.JComboBox();
        comboQuery = new javax.swing.JComboBox();
        comboFormat = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        comboReport = new javax.swing.JComboBox();
        btnReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Assignment 4 - A Flight Schedule");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Inputs"));

        jLabel2.setText("Locations:");

        txtLocationsFile.setText("locations.csv");

        jLabel1.setText("Flights:");

        txtFlightsFile.setText("flights.csv");

        btnLoad.setMnemonic('L');
        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnAllFlightsDisplayFormat.setMnemonic('D');
        btnAllFlightsDisplayFormat.setText("All Flights in Display Format");
        btnAllFlightsDisplayFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllFlightsDisplayFormatActionPerformed(evt);
            }
        });

        btnAllFlightsArchiveFormat.setText("All Flights in Archive Format");
        btnAllFlightsArchiveFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllFlightsArchiveFormatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocationsFile)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFlightsFile, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAllFlightsDisplayFormat)
                        .addGap(18, 18, 18)
                        .addComponent(btnAllFlightsArchiveFormat)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLocationsFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoad)
                    .addComponent(jLabel1)
                    .addComponent(txtFlightsFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAllFlightsDisplayFormat)
                    .addComponent(btnAllFlightsArchiveFormat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtStatus.setEditable(false);
        txtStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Queries"));

        btnQuery.setMnemonic('X');
        btnQuery.setText("Execute Query");
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });

        comboParameter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboQuery.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboFormat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQuery)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuery))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Reports"));

        comboReport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnReport.setText("Display Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReport)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReport))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed

        if (!createLocations(txtLocationsFile.getText()))
            return;
        if (!createFlights(txtFlightsFile.getText()))
            return;
        if (locations == null || allFlights == null)
            return;

        schedule = new FlightSchedule(allFlights);

        txtStatus.setText("Data files loaded");
        activateReadyState(true);
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed

        String query = comboQuery.getSelectedItem().toString();
        String param = comboParameter.getSelectedItem().toString();
        String format = comboFormat.getSelectedItem().toString();
        Flight[] flights = null;

        if (query.equals(Common.FLIGHT_TYPE))
            flights = schedule.getFlightsByType(param);
        else if (query.equals(Common.DESTINATION)) {
            param = param.substring(0, 3); // extract Location Code ONLY
            flights = schedule.getFlightsByDestination(param);
        } else
            return;

        int totalWeight = findTotalWeight(flights);
        
        int numFlights = flights.length;
        
        if (format.equals(Common.ARCHIVE_FORMAT))
            outputFlightsInArchiveFormat(flights);
        else if (format.equals(Common.DISPLAY_FORMAT))
            outputFlightsInDisplayFormat(flights);
        
        txtOutput.append("\n" + "# Flights = " + numFlights);
        txtOutput.append("\n" + "Total Weight = " + Common.format(totalWeight));


    }//GEN-LAST:event_btnQueryActionPerformed

private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed

    String report = comboReport.getSelectedItem().toString();

    if (report.equals(Common.SUMMARY_FLIGHT_TYPE))
        reportSummaryByFlightType();
    else if (report.equals(Common.SUMMARY_DESTINATION))
        reportSummaryByDestination();
    else if (report.equals(Common.POLICY_ERRORS))
        runPolicyCheckReport();

}//GEN-LAST:event_btnReportActionPerformed

    private void btnAllFlightsDisplayFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllFlightsDisplayFormatActionPerformed

        outputFlightsInDisplayFormat(schedule.getAllFlights());

    }//GEN-LAST:event_btnAllFlightsDisplayFormatActionPerformed

    private void btnAllFlightsArchiveFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllFlightsArchiveFormatActionPerformed

        outputFlightsInArchiveFormat(schedule.getAllFlights());

    }//GEN-LAST:event_btnAllFlightsArchiveFormatActionPerformed

    private void reportSummaryByFlightType() {
        // TODO-C1        
        txtOutput.setText("Summary Report By FlightType\n\n");     
        reportSummaryType("Cargo");
        reportSummaryType("Passenger");
        reportSummaryType("Training");           
        txtOutput.append("\r\n------------------------------------------------------------------------");
        reportSummaryType("All");

    }

    private void reportSummaryByDestination() {
        // TODO-C2
        txtOutput.setText("Summary Report By Destination\n\n");
        for(Location loc : locations){
            reportSummaryDestination(loc.getLocationCode());
        }
        txtOutput.append("\r\n------------------------------------------------------------------------");
        reportSummaryType("All");
    }
    
    private void reportSummaryType(String type){
        Flight[] flights = null;
        if(type.equals("Cargo")){
            flights = schedule.getFlightsByType("Cargo");        
            txtOutput.append(flights.length + " Cargo Flights \t Weight = " + Common.format(findTotalWeight(flights)));
        }else if(type.equals("Passenger")){
            flights = schedule.getFlightsByType("Passenger");  
            txtOutput.append("\r\n" + flights.length + " Passenger Flights \t Weight = " + Common.format(findTotalWeight(flights)));
        }else if (type.equals("Training")){
            flights = schedule.getFlightsByType("Training");  
            txtOutput.append("\r\n" + flights.length + " Training Flights \t Weight = " + Common.format(findTotalWeight(flights)));
        }else if (type.equals("All")){
             flights = schedule.getAllFlights();
            txtOutput.append("\r\n" + flights.length + " Flights \t Weight = " + Common.format(findTotalWeight(flights))); 
        }else{
            txtOutput.append("Error - unknown type: " + type);

        }
    }
    
    private void reportSummaryDestination(String loc){
        Flight[] flights = null;
        flights = schedule.getFlightsByDestination(loc);
        if(flights.length > 0){
           txtOutput.append("\r\n " + flights.length + " Flights to " + loc + "  \t Weight = " + Common.format(findTotalWeight(flights)));  
        }
           
    }

    private void outputFlightsInArchiveFormat(Flight[] flights) {

        txtOutput.setText("");
        for (Flight flight : flights)
            txtOutput.append(flight.toArchiveFormat() + "\n");
    }

    private void outputFlightsInDisplayFormat(Flight[] flights) {

        txtOutput.setText("");
        for (Flight flight : flights)
            txtOutput.append(flight.toDisplayReport() + "\n");
    }

    private int findTotalWeight(Flight[] flights) {

        int res = 0;
        for (Flight flight : flights)
            res += flight.calculateWeight();
        return res;
    }

    /**
     * Creates Location objects from data in a file.
     *
     * @param fileName the file containing the location data
     * @return an array of Location objects
     */
    private boolean createLocations(String fileName) {
        ArrayList<Location> result = new ArrayList<>();
        try {
            Scanner sc = new Scanner(new File(fileName));
            while (sc.hasNextLine()) {
                String line = sc.nextLine();
                Location loc = Location.parseCSV(line);
                if (loc == null)
                    System.out.println("error parsing Location: line=" + line);
                else
                    result.add(loc);
            }
            System.out.println("" + result.size() + " Locations loaded");
            this.locations = result.toArray(Location[]::new);
            return true;
        } catch (Exception ex) {
            System.out.println("Location Parse error, msg=" + ex.getMessage());
            return false;
        }
    }

    /**
     * Creates Flight objects from data in a file.
     *
     * @param fileName the file containing the flight data
     * @return an array of Flight objects
     */
    private boolean createFlights(String fileName) {

        // TODO-A5 complete this method
        ArrayList<Flight> result = new ArrayList<>();
        
        try{
            Scanner sc = new Scanner(new File(fileName));
            while (sc.hasNextLine()) {
                String line = sc.nextLine();
                System.out.println(line);
                Flight newFlight = Flight.parseCSV(line, this);

                if (newFlight == null)
                    System.out.println("error parsing Flight: line=" + line);
                else
                     result.add(newFlight);
            }
            allFlights = result.toArray(Flight[]::new);
            return true;
        }catch(Exception ex){
            System.out.println("Flight Parse error, msg=" + ex.getMessage());
            return false;
        }
  
    }

    /**
     * Finds the Location object with the specified location code.
     *
     * @param locationCode the three-letter location code to match
     * @return the Location object with that code.
     */
    @Override
    public Location findLocation(String locationCode) {
        for (Location loc : locations)
            if (loc.getLocationCode().equals(locationCode))
                return loc;
        return null;
    }

    private void runPolicyCheckReport() {
        // TODO-D2
        Flight[] flights = schedule.getAllFlights();
        
        String[] policies = PolicyChecker.runPolicyChecks(flights);
        
        int count = 0;
        
        for(int i = 0; i < flights.length; i++){
            Flight currentFlight = flights[i];
            String currentError = policies[i];
            if(!currentError.equals(Common.NO_ERROR)){
                txtOutput.append("\r\n\r\n" + currentFlight.toArchiveFormat());
                txtOutput.append("\r\n" + currentError);
                count++;
            }
        }
        txtOutput.append("\r\n\r\n " + count + " Flights found with errors.");       
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new FlightsMainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllFlightsArchiveFormat;
    private javax.swing.JButton btnAllFlightsDisplayFormat;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnQuery;
    private javax.swing.JButton btnReport;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboFormat;
    private javax.swing.JComboBox comboParameter;
    private javax.swing.JComboBox comboQuery;
    private javax.swing.JComboBox comboReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFlightsFile;
    private javax.swing.JTextField txtLocationsFile;
    private javax.swing.JTextArea txtOutput;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

}
